kind: Deployment
apiVersion: apps/v1
metadata:
 name: eurekadeployment
spec:
 selector:
  matchLabels:
    app: eurekapod
 replicas: 1
 template:
   metadata:
    labels:
     app: eurekapod
   spec:
    containers:
     - name: eurekacontainer
       image: aarfi/eureka:1
       ports:
        - containerPort: 8761        