kind: Deployment
apiVersion: apps/v1
spec:
 selector:
   matchLabels:
    app: configpod
 replicas: 2
 template:
  metadata:
   labels:
    app: configpod
  spec:
   containers:
    - name: configcontainer
      image: aarfi/getconfig:1
      ports:
       - containerPort: 9191     
metadata:
  name: getconfigdeployment