kind: Deployment
apiVersion: apps/v1 
spec:
 selector:
  matchLabels:
   app: myfirstpod
 replicas: 2 
 template:
  metadata:
   labels:
    app: myfirstpod
  spec:
   containers:
    - name: my1
      image: aarfi/boardingimage:2
      ports:
       - containerPort: 9090
 
  
metadata:
  name: myfirstdeployment